# This is a basic workflow that is manually triggered

name: auto-update

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule: 
    - cron: "0 13 * * 1"
  workflow_dispatch:


jobs:

  autoupdate:

    runs-on: ubuntu-latest

    steps:
    - 
      name: checkout current project  
      uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.head_ref }}
    - 
      name: run update.sh
      run: ./update.sh
    - 
      name: commit updated docker files
      uses: stefanzweifel/git-auto-commit-action@v4.12.0
      with:
        commit_message: Auto-update dockerfiles
