name: build-docker

on:
  workflow_dispatch:
#  push:


jobs:

  buildx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10.2, 10.3, 10.4]
        include:
          - version: 10.4
            latest: "true"
    steps:
      - 
        name: Prepare
        id: prepare
        env:
          VERSION: ${{ matrix.version }}
          LATEST: ${{ matrix.latest }}
        run: |
          echo ::set-output name=docker_image::ghcr.io/ejsmit/mariadb
          echo ::set-output name=version::$VERSION
          echo ::set-output name=docker_username::ejsmit
          TAG=ghcr.io/ejsmit/mariadb:${VERSION}
          if [[ $LATEST == "true" ]]; then
            LATEST_TAG=",ghcr.io/ejsmit/mariadb:latest"
          fi
          echo ::set-output name=docker_tags::${TAG}${LATEST_TAG}
      - 
        name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        uses: docker/setup-buildx-action@v1.4.0
        id: buildx
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ejsmit
          password: ${{ secrets.CR_PAT }}
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        with:
          context: ${{ matrix.version }}
          file: ./${{ matrix.version }}/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.prepare.outputs.docker_tags }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}



